### ISSUE TITLE
Feedback for “Configuration”

### ISSUE THREAD

**Issue by frankdejonge** [autometrics-dev/docs#39]
The link to the TypeScript API Reference is broken, it should link to "https://github.com/autometrics-dev/autometrics-ts/tree/main/packages/autometrics/reference". The current link is directed to "https://github.com/autometrics-dev/autometrics-ts/tree/main/packages/lib/reference", which does not exist.. Specifically, `/lib/` -> `/autometrics/`.

**Comment by keturiosakys** [comment]
Hey @frankdejonge thanks for reporting these! We've recently moved a lot of things around in the TypeScript repo and I'm still catching up with some broken links. Will fix these up shortly!
