### ISSUE TITLE
Make a page for Configuring Prometheus

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/docs#8]
So that we can link to it directly

It can also mention that you need to configure Prometheus to scrape metrics from your application (and maybe even include a diagram showing how it works).

**Comment by keturiosakys** [comment]
We currently have: https://docs.autometrics.dev/configuring-prometheus/local and other subsites for configuring Prometheus in different environments (Fly.io and Kubernetes). Do you think we should expand it with, e.g. explaining how it works?

**Comment by emschwartz** [comment]
I just meant there should be an actual page for `configuring-prometheus` so that you can link directly to it (as opposed to one of the pages for local, etc)
